TOP=../..

include $(TOP)/configure/CONFIG

#=============================
# build a library


# INC+=evrTime.h
# DBDINC += longSubRecord
# DBD += evrSupport.dbd
# LIBRARY_IOC = evrSupport
#evrSupport_SRCS += evrEvInvariantDelay.c
# evrSupport_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES

#----------------------------------------
#  ADD RULES AFTER THIS LINE

